packages:
  - packages/*
catalog:
  # deltachat specific
  '@privitty/jsonrpc-client': 2.48.3
  '@privitty/stdio-rpc-server': 2.48.3
  '@webxdc/types': ^2.1.2
  'calls-webapp': 'github:deltachat/calls-webapp#build-for-deltachat-desktop'

  # dependencies
  '@types/mime-types': ^2.1.4
  mime-types: ^2.1.35

  # tools / dev dependencies
  sass: ^1.86.3
  typescript: ^5.9.2
  typescript-plugin-css-modules: ^5.2.0
  '@types/node': ^20.14.13
